export type AnimalRarity = 'common' | 'rare' | 'legendary';
export type AnimalType =
  | 'squirrel' | 'pigeon' | 'dog' | 'robin'
  | 'cat' | 'raccoon' | 'sparrow'
  | 'rabbit' | 'turtle' | 'hawk'
  | 'seagull' | 'sandpiper' | 'beachcat'
  | 'pelican' | 'dolphin'
  | 'chipmunk' | 'deer' | 'woodpecker' | 'turkey'
  | 'fox' | 'beaver' | 'hummingbird' | 'bluebird'
  | 'heron' | 'bear' | 'owl' | 'skunk' | 'bobcat'
  | 'moose' | 'firefly' | 'otter' | 'loon' | 'wolf'
  | 'seal' | 'plover' | 'coyote' | 'whale'
  | 'porcupine' | 'falcon' | 'lynx' | 'eagle'
  | 'groundhog'
  | 'seaturtle' | 'flamingo' | 'parrot' | 'jaguar'
  | 'reddeer' | 'wildboar' | 'stork' | 'europeanfox'
  | 'chinesedolphin' | 'macaque' | 'blackkite' | 'pangolin';

export interface Animal {
  id: string;
  name: string;
  type: AnimalType;
  emoji: string;
  rarity: AnimalRarity;
  locationIds: string[];
  funFact: string;
  greetings: string[];
  bodyColor: string;
  accentColor: string;
  xpReward: number;
  friendshipLines: string[];
  /** How many friendship hearts needed to become a companion (3=common, 4=rare, 5=legendary) */
  companionThreshold: number;
  hidden?: boolean;
  minVisits?: number;
}

export const ANIMALS: Animal[] = [
  // ── Prospect Park, Brooklyn ──────────────────────────────────────
  {
    id: 'squirrel',
    name: 'Sammy the Squirrel',
    type: 'squirrel',
    emoji: '🐿️',
    rarity: 'common',
    locationIds: ['prospect-park', 'central-park'],
    funFact: 'Squirrels plant thousands of trees every year by forgetting where they buried their acorns!',
    greetings: ['Chitter chitter! Got any acorns?', 'Ooh, a visitor! Hello!', 'I just found the BEST acorn. Want to see?'],
    bodyColor: '#8B5E3C',
    accentColor: '#D4A464',
    xpReward: 10,
    friendshipLines: ['You remembered me!', 'Best friends share acorns!'],
    companionThreshold: 3,
  },
  {
    id: 'pigeon',
    name: 'Pearl the Pigeon',
    type: 'pigeon',
    emoji: '🕊️',
    rarity: 'common',
    locationIds: ['prospect-park', 'brooklyn-heights'],
    funFact: 'Pigeons can find their way home from over 1,000 miles away. They have built-in GPS!',
    greetings: ['Coo coo! Welcome to Brooklyn!', 'Coo! I love visitors!', 'I deliver messages! What\'s yours?'],
    bodyColor: '#9E9E9E',
    accentColor: '#7B68EE',
    xpReward: 8,
    friendshipLines: ["Coo coo! My bestie!", "I'll show you all my favorite spots!"],
    companionThreshold: 3,
  },
  {
    id: 'dog',
    name: 'Biscuit the Dog',
    type: 'dog',
    emoji: '🐕',
    rarity: 'common',
    locationIds: ['prospect-park'],
    funFact: 'Dogs can smell up to 100,000 times better than humans — they could find a lost sock in a whole city!',
    greetings: ['WOOF! WOOF! I LOVE YOU!', 'Play with me? PLEASE?', 'I can fetch ANYTHING. Watch me!'],
    bodyColor: '#C8A96E',
    accentColor: '#F5DEB3',
    xpReward: 15,
    friendshipLines: ['Best friend forever! WOOF!', 'You\'re my favorite person!'],
    companionThreshold: 3,
  },
  {
    id: 'robin',
    name: 'Rosa the Robin',
    type: 'robin',
    emoji: '🐦',
    rarity: 'common',
    locationIds: ['prospect-park'],
    funFact: 'A robin\'s red chest is how it tells other robins "this is my tree!" It\'s like wearing a bright shirt.',
    greetings: ['Tweet tweet! Beautiful day!', 'I just got back from the south!', 'I can hear worms underground — can you?'],
    bodyColor: '#5B3E2B',
    accentColor: '#E07B39',
    xpReward: 10,
    friendshipLines: ['I\'ll sing just for you!', 'You\'re as sweet as a worm… I mean, berries!'],
    companionThreshold: 3,
  },

  // ── Brooklyn Heights / DUMBO ─────────────────────────────────────
  {
    id: 'cat',
    name: 'Cleo the Cat',
    type: 'cat',
    emoji: '🐈',
    rarity: 'rare',
    locationIds: ['brooklyn-heights'],
    funFact: 'Cats can jump up to six times their own height — that would be like you jumping to the top of a house!',
    greetings: ['Mrrrow… I suppose you can approach.', '*blinks slowly* This means I trust you.', 'I\'ve been sitting here for three hours. I\'m fine.'],
    bodyColor: '#E8D5B7',
    accentColor: '#B8860B',
    xpReward: 20,
    friendshipLines: ['I\'ve decided you\'re acceptable.', '...You may pet me. Just this once.'],
    companionThreshold: 4,
  },
  {
    id: 'raccoon',
    name: 'Remy the Raccoon',
    type: 'raccoon',
    emoji: '🦝',
    rarity: 'rare',
    locationIds: ['brooklyn-heights'],
    funFact: 'Raccoons wash their food before eating it, just like you wash your hands before dinner!',
    greetings: ['*rustles in trash* Oh! Hi there!', 'Shhh, I\'m being sneaky!', 'I found a pizza slice AND a breadstick tonight. Amazing.'],
    bodyColor: '#696969',
    accentColor: '#2C2C2C',
    xpReward: 20,
    friendshipLines: ['I saved you some pizza!', 'You\'re the best sneaky partner!'],
    companionThreshold: 4,
  },
  {
    id: 'sparrow',
    name: 'Sunny the Sparrow',
    type: 'sparrow',
    emoji: '🐦',
    rarity: 'common',
    locationIds: ['brooklyn-heights'],
    funFact: 'Sparrows take "dust baths" — they roll in dirt to keep their feathers clean and bug-free!',
    greetings: ['Cheep cheep! Hello hello!', 'I can show you the best crumbs!', 'I\'ve visited 47 countries! (Okay, 2. But still!)'],
    bodyColor: '#A0826D',
    accentColor: '#E8C99A',
    xpReward: 8,
    friendshipLines: ['Cheep cheep cheep! (That means best friends!)'],
    companionThreshold: 3,
  },

  // ── Central Park, Manhattan ───────────────────────────────────────
  {
    id: 'rabbit',
    name: 'Rosie the Rabbit',
    type: 'rabbit',
    emoji: '🐇',
    rarity: 'rare',
    locationIds: ['central-park'],
    funFact: 'Rabbits can\'t be sick to their stomachs — so they\'re very careful to only eat safe plants. Smart!',
    greetings: ['*twitches nose* Ooh, someone new!', 'Hop hop! Nice to meet you!', 'My nose knows 700 smells. Yours is... pleasant!'],
    bodyColor: '#E8D5B7',
    accentColor: '#FFB6C1',
    xpReward: 25,
    friendshipLines: ['I\'ll share my clover patch!', 'Best friends hop together!'],
    companionThreshold: 4,
  },
  {
    id: 'turtle',
    name: 'Theo the Turtle',
    type: 'turtle',
    emoji: '🐢',
    rarity: 'rare',
    locationIds: ['central-park'],
    funFact: 'Turtles have been on Earth for over 200 million years — they lived alongside dinosaurs!',
    greetings: ['…Hello there. I\'m Theo.', 'Take your time. I\'ll be here.', 'I\'ve seen empires rise and fall. You seem nice.'],
    bodyColor: '#4CAF50',
    accentColor: '#2E7D32',
    xpReward: 25,
    friendshipLines: ['Slow and steady wins the friendship.', 'I\'ve saved you a warm sunny rock.'],
    companionThreshold: 4,
  },
  {
    id: 'hawk',
    name: 'Hunter the Red-tailed Hawk',
    type: 'hawk',
    emoji: '🦅',
    rarity: 'legendary',
    locationIds: ['central-park'],
    funFact: 'Red-tailed hawks can spot a mouse from 100 feet in the air! Their eyes are 8 times sharper than yours.',
    greetings: ['SCREEEE! A brave explorer approaches.', 'I\'ve been watching you from way up high.', 'From my perch I can see all of Central Park. And you.'],
    bodyColor: '#8B4513',
    accentColor: '#CD853F',
    xpReward: 50,
    friendshipLines: ['You are worthy of the skies!', 'I will keep watch over you, little explorer.'],
    companionThreshold: 5,
  },
  // ── Rockaway Beach ───────────────────────────────────────────────
  {
    id: 'seagull',
    name: 'Gully the Seagull',
    type: 'seagull',
    emoji: '🦢',
    rarity: 'common',
    locationIds: ['rockaway-beach'],
    funFact: 'Seagulls are so smart they do a funny rain dance to trick worms into coming out of the ground!',
    greetings: ['SQUAWK! Is that a snack?', 'I LOVE the beach! Don\'t you?', 'I once stole a hot dog from a man twice my size. Legendary.'],
    bodyColor: '#F5F5F5',
    accentColor: '#E0E0E0',
    xpReward: 12,
    friendshipLines: ['You\'re my favorite snack-sharer!', 'SQUAWK means I love you!'],
    companionThreshold: 3,
  },
  {
    id: 'beachcat',
    name: 'Sandy the Beach Cat',
    type: 'beachcat',
    emoji: '🐱',
    rarity: 'rare',
    locationIds: ['rockaway-beach'],
    funFact: 'Some cats love water! Wild cats like fishing cats are great swimmers and even dive for fish.',
    greetings: ['Mew! The salt breeze suits me.', 'I nap under the boardwalk. Wanna join?', 'I\'ve watched a thousand sunsets. This one\'s my favorite.'],
    bodyColor: '#E8C090',
    accentColor: '#A0522D',
    xpReward: 22,
    friendshipLines: ['You found my secret beach spot!', 'Purrrr… sunbeams and friends!'],
    companionThreshold: 4,
  },
  {
    id: 'pelican',
    name: 'Pepper the Brown Pelican',
    type: 'pelican',
    emoji: '🦢',
    rarity: 'common',
    locationIds: ['rockaway-beach'],
    funFact: 'Brown pelicans dive headfirst from 60 feet in the air to catch fish — they can spot fish from way up high!',
    greetings: ['SPLASH! Did you see that dive?', 'My beak can hold more than my belly! Cool, right?', 'I\'m the best diver on this beach. Don\'t argue.'],
    bodyColor: '#8B7355',
    accentColor: '#FFE4B5',
    xpReward: 15,
    friendshipLines: ['I\'ll show you my best dive!', 'Real pals share fish!'],
    companionThreshold: 3,
  },
  {
    id: 'dolphin',
    name: 'Desi the Bottlenose Dolphin',
    type: 'dolphin',
    emoji: '🐬',
    rarity: 'rare',
    locationIds: ['rockaway-beach'],
    funFact: 'Dolphins have names for each other! They use unique whistles to call their friends — just like a phone!',
    greetings: ['*leaps out of the water* HI!!!', 'EEEEE! (That means hello in dolphin!)', 'I swam here all the way from the deep ocean just to see you!'],
    bodyColor: '#5B9BD5',
    accentColor: '#BDD7EE',
    xpReward: 35,
    friendshipLines: ['I\'ll teach you the dolphin handshake!', 'Best wave-riders forever!'],
    companionThreshold: 4,
  },

  // ── Staten Island Greenbelt ───────────────────────────────────────
  {
    id: 'chipmunk',
    name: 'Chester the Chipmunk',
    type: 'chipmunk',
    emoji: '🐿️',
    rarity: 'common',
    locationIds: ['staten-island'],
    funFact: 'Chipmunks can carry as many as 165 acorns at a time in their stretchy cheek pouches!',
    greetings: ['Chip chip! I\'m storing for winter!', 'Look at my cheeks! So full!', 'Want to see how fast I can run? Ready, set—*gone*'],
    bodyColor: '#C17817',
    accentColor: '#F5DEB3',
    xpReward: 15,
    friendshipLines: ['I saved you some seeds!', 'Chip chip hooray for friends!'],
    companionThreshold: 3,
  },
  {
    id: 'deer',
    name: 'Daisy the White-tailed Deer',
    type: 'deer',
    emoji: '🦌',
    rarity: 'rare',
    locationIds: ['staten-island'],
    funFact: 'Baby deer are called fawns, and their spots help them hide in dappled forest sunlight!',
    greetings: ['*gentle sniff* Hello, kind explorer.', 'I move so quietly even the birds don\'t hear me.', 'My family has lived in this forest for 10 years. Welcome!'],
    bodyColor: '#C8854A',
    accentColor: '#F5DEB3',
    xpReward: 30,
    friendshipLines: ['I\'ll share my quiet meadow.', 'You have the gentlest footsteps.'],
    companionThreshold: 4,
  },
  {
    id: 'woodpecker',
    name: 'Woody the Pileated Woodpecker',
    type: 'woodpecker',
    emoji: '🐦',
    rarity: 'common',
    locationIds: ['staten-island'],
    funFact: 'Pileated woodpeckers hammer trees 20 times per second! Their brains have special cushioning so they never get headaches.',
    greetings: ['RAT-A-TAT-TAT! Oh! A visitor!', 'Sorry about the noise. I\'m renovating this oak.', 'I found 40 carpenter ants today. Personal best!'],
    bodyColor: '#2C2C2C',
    accentColor: '#CC0000',
    xpReward: 15,
    friendshipLines: ['I\'ll carve your name in my favorite tree!', 'Drum roll for my best friend!'],
    companionThreshold: 3,
  },
  {
    id: 'turkey',
    name: 'Terrance the Wild Turkey',
    type: 'turkey',
    emoji: '🦃',
    rarity: 'rare',
    locationIds: ['staten-island'],
    funFact: 'Wild turkeys can run 25 miles per hour and fly up to 55 miles per hour — and they roost in trees at night!',
    greetings: ['GOBBLE GOBBLE! Good morning!', 'Don\'t let the size fool you — I\'m quite fast!', 'I\'ve got 5,000 feathers. I counted. Twice.'],
    bodyColor: '#4A3728',
    accentColor: '#CC6600',
    xpReward: 28,
    friendshipLines: ['I\'ll gobble your name to the whole forest!', 'You\'re worth fanning my tail feathers for!'],
    companionThreshold: 4,
  },

  // ── Hudson Valley ────────────────────────────────────────────────
  {
    id: 'fox',
    name: 'Fern the Fox',
    type: 'fox',
    emoji: '🦊',
    rarity: 'rare',
    locationIds: ['hudson-valley'],
    funFact: 'Foxes use the Earth\'s magnetic field like a compass to help them pounce on mice buried under snow!',
    greetings: ['Oh! You\'re clever enough to find me!', 'I was watching from the bushes.', 'Most explorers give up. You didn\'t. Impressive.'],
    bodyColor: '#E07B39',
    accentColor: '#FFFFFF',
    xpReward: 35,
    friendshipLines: ['You\'re almost as clever as me!', 'Friends share their berry patches!'],
    companionThreshold: 4,
  },
  {
    id: 'beaver',
    name: 'Bruno the Beaver',
    type: 'beaver',
    emoji: '🦫',
    rarity: 'rare',
    locationIds: ['hudson-valley'],
    funFact: 'Beavers are nature\'s engineers! Their dams create ponds that give homes to hundreds of other animals.',
    greetings: ['I\'m building a dam! Wanna help?', '*slaps tail* Oh! Hello there!', 'This dam took me 3 weeks. I\'m very proud.'],
    bodyColor: '#8B5E3C',
    accentColor: '#5C4033',
    xpReward: 30,
    friendshipLines: ['You can live in my pond anytime!', 'I\'ll build you a little bridge!'],
    companionThreshold: 4,
  },
  {
    id: 'hummingbird',
    name: 'Ruby the Ruby-throated Hummingbird',
    type: 'hummingbird',
    emoji: '🐦',
    rarity: 'common',
    locationIds: ['hudson-valley'],
    funFact: 'Hummingbirds beat their wings 80 times per second and are the only birds that can fly backward!',
    greetings: ['*hovers* Hi! I can\'t stop — got 1,000 flowers to visit!', 'Whoosh! Did you blink? I was already here!', 'I drink twice my body weight in nectar every day. BUSY.'],
    bodyColor: '#2D8B47',
    accentColor: '#FF3333',
    xpReward: 18,
    friendshipLines: ['I\'ll hover just for you!', 'You\'re sweeter than any flower!'],
    companionThreshold: 3,
  },
  {
    id: 'bluebird',
    name: 'Bella the Eastern Bluebird',
    type: 'bluebird',
    emoji: '🐦',
    rarity: 'common',
    locationIds: ['hudson-valley'],
    funFact: 'Eastern bluebirds are so blue because of tiny light-scattering structures in their feathers — there\'s actually no blue pigment!',
    greetings: ['Hello! Isn\'t this valley beautiful?', 'I\'m the happiest bird you\'ll meet today!', 'Blue sky, blue me — we match! 💙'],
    bodyColor: '#1E90FF',
    accentColor: '#FF8C00',
    xpReward: 15,
    friendshipLines: ['You bring color to my day!', 'Friends make the valley sing!'],
    companionThreshold: 3,
  },

  // ── Catskill Mountains ───────────────────────────────────────────
  {
    id: 'bear',
    name: 'Bernadette the Black Bear',
    type: 'bear',
    emoji: '🐻',
    rarity: 'legendary',
    locationIds: ['catskills'],
    funFact: 'Black bears are not really black — they come in brown, cinnamon, and even blonde colors! They\'re also amazing swimmers.',
    greetings: ['ROAR! ...Just kidding. Hi there! I\'m gentle!', '*sniffs air* You smell like adventure!', 'I can smell your trail mix from a mile away. Sharing is caring…'],
    bodyColor: '#2C2C2C',
    accentColor: '#5C4033',
    xpReward: 60,
    friendshipLines: ['I give the BEST bear hugs!', 'Come find berries with me!'],
    companionThreshold: 5,
  },
  {
    id: 'owl',
    name: 'Ophelia the Barred Owl',
    type: 'owl',
    emoji: '🦉',
    rarity: 'legendary',
    locationIds: ['catskills'],
    funFact: 'Owls can turn their heads almost all the way around — 270 degrees! That\'s like looking behind you without moving your body.',
    greetings: ['Who cooks for you? WHO COOKS FOR YOU?', 'Hoo hoo… a night-time explorer!', '*rotates head 270°* Just making sure we\'re alone.'],
    bodyColor: '#8B7355',
    accentColor: '#D2B48C',
    xpReward: 55,
    friendshipLines: ['Wisdom and friendship go together.', 'I\'ll keep watch while you sleep, little explorer.'],
    companionThreshold: 5,
  },
  {
    id: 'skunk',
    name: 'Stella the Striped Skunk',
    type: 'skunk',
    emoji: '🦨',
    rarity: 'common',
    locationIds: ['catskills'],
    funFact: 'Skunks always give a warning before spraying — they stomp, hiss, and do a handstand! Most animals run away before anything happens.',
    greetings: ['Don\'t worry, I only spray bad guys!', '*does a little handstand warning* Just kidding! Hello!', 'I\'m actually very sweet. The smell is just… insurance.'],
    bodyColor: '#2C2C2C',
    accentColor: '#FFFFFF',
    xpReward: 18,
    friendshipLines: ['I\'ll never spray a friend!', 'You passed the smell test — you\'re trustworthy!'],
    companionThreshold: 3,
  },
  {
    id: 'bobcat',
    name: 'Bobby the Bobcat',
    type: 'bobcat',
    emoji: '🐱',
    rarity: 'rare',
    locationIds: ['catskills'],
    funFact: 'Bobcats are so quiet that researchers tracked one for 6 months and found it lived within a mile of a busy road — and nobody had ever seen it!',
    greetings: ['*appears from nowhere* Hello.', 'You have very good eyes. Most explorers never find me.', 'I live here but I am a mystery. Even to myself.'],
    bodyColor: '#C8A464',
    accentColor: '#8B6914',
    xpReward: 42,
    friendshipLines: ['I\'ll let you into my secret mountain territory!', 'You see me. That makes you special.'],
    companionThreshold: 4,
  },

  // ── Adirondacks ──────────────────────────────────────────────────
  {
    id: 'otter',
    name: 'Ollie the River Otter',
    type: 'otter',
    emoji: '🦦',
    rarity: 'rare',
    locationIds: ['adirondacks'],
    funFact: 'Otters hold hands while they sleep in the water so they don\'t drift away from each other. How sweet!',
    greetings: ['Wheee! Slide with me!', 'I can show you my favorite river slide!', '*holds your hand* Don\'t want you drifting away!'],
    bodyColor: '#6B4F3A',
    accentColor: '#D2B48C',
    xpReward: 40,
    friendshipLines: ['Hold my paw? otter-ly delighted!', 'Best slidemates forever!'],
    companionThreshold: 4,
  },
  {
    id: 'moose',
    name: 'Magnus the Moose',
    type: 'moose',
    emoji: '🫎',
    rarity: 'legendary',
    locationIds: ['adirondacks'],
    funFact: 'Moose can dive 20 feet underwater to eat plants off the lake bottom, and they can swim for miles!',
    greetings: ['*gentle honk* Well, hello little one.', 'I don\'t see many explorers up this far north!', 'These antlers took all spring to grow. Please admire them.'],
    bodyColor: '#5C4033',
    accentColor: '#3E2723',
    xpReward: 65,
    friendshipLines: ['I shall carry you over the mountains!', 'You are the bravest explorer I\'ve met.'],
    companionThreshold: 5,
  },
  {
    id: 'loon',
    name: 'Lenny the Common Loon',
    type: 'loon',
    emoji: '🐦',
    rarity: 'rare',
    locationIds: ['adirondacks'],
    funFact: 'Loons have solid bones (unlike most birds) so they can dive over 200 feet deep! Their haunting call echoes across lakes for miles.',
    greetings: ['*eerie, beautiful wail across the lake* Hello!', 'That cry you heard? That was me saying hi.', 'I am the voice of the Adirondack wilderness.'],
    bodyColor: '#1A1A1A',
    accentColor: '#FFFFFF',
    xpReward: 38,
    friendshipLines: ['I\'ll sing your favorite song across the lake!', 'The wild calls out your name now, friend.'],
    companionThreshold: 4,
  },
  {
    id: 'wolf',
    name: 'Winona the Eastern Timber Wolf',
    type: 'wolf',
    emoji: '🐺',
    rarity: 'legendary',
    locationIds: ['adirondacks'],
    funFact: 'Wolf packs are family groups. The "alpha" wolves are just the parents — they lead through love, not fighting!',
    greetings: ['*low howl* The pack has been watching you.', 'You passed through our territory with respect. We noticed.', 'Wolves remember every face. I will remember yours.'],
    bodyColor: '#6B6B6B',
    accentColor: '#D4D4D4',
    xpReward: 70,
    friendshipLines: ['You are pack now. The forest protects you.', 'I howl your name to the moon each night.'],
    companionThreshold: 5,
  },

  // ── Cape Cod, Massachusetts ─────────────────────────────────────
  {
    id: 'seal',
    name: 'Shelby the Harbor Seal',
    type: 'seal',
    emoji: '🦭',
    rarity: 'rare',
    locationIds: ['cape-cod'],
    funFact: 'Harbor seals can hold their breath for up to 30 minutes and dive over 1,400 feet deep!',
    greetings: ['*splashes happily* A visitor! How exciting!', 'I love floating on my back in the waves!', 'Watch me spin! I\'ve been practicing!'],
    bodyColor: '#8D9B9F',
    accentColor: '#B0BEC5',
    xpReward: 40,
    friendshipLines: ['I\'ll show you my favorite sunny rock!', 'You\'re my favorite land-friend!'],
    companionThreshold: 4,
  },
  {
    id: 'plover',
    name: 'Pippa the Piping Plover',
    type: 'plover',
    emoji: '🐦',
    rarity: 'rare',
    locationIds: ['cape-cod'],
    funFact: 'Piping plovers are tiny shorebirds that blend into the sand so well, people walk right past them without noticing!',
    greetings: ['Peep peep! Watch where you step please!', 'My nest is hidden right here in the sand!', 'I am VERY hard to find. You must be a great explorer!'],
    bodyColor: '#E8D5B7',
    accentColor: '#C8A96E',
    xpReward: 35,
    friendshipLines: ['I trust you to be careful near my nest!', 'Peep! That means you\'re special!'],
    companionThreshold: 4,
  },
  {
    id: 'coyote',
    name: 'Coby the Eastern Coyote',
    type: 'coyote',
    emoji: '🐺',
    rarity: 'legendary',
    locationIds: ['cape-cod'],
    funFact: 'Eastern coyotes are part wolf and part coyote — they\'re bigger and smarter than their western cousins!',
    greetings: ['*howls softly* The moon sent you to me.', 'I\'ve been watching you from the dunes…', 'I\'ve lived on this cape for 7 years. You\'re the first to really look for me.'],
    bodyColor: '#9E8B6E',
    accentColor: '#D2B48C',
    xpReward: 55,
    friendshipLines: ['I\'ll sing you a moonlight song!', 'You run with the pack now, friend.'],
    companionThreshold: 5,
  },
  {
    id: 'whale',
    name: 'Hank the Humpback Whale',
    type: 'whale',
    emoji: '🐳',
    rarity: 'legendary',
    locationIds: ['cape-cod'],
    funFact: 'Humpback whales sing the longest and most complex songs in the animal kingdom — a single song can last 20 minutes!',
    greetings: ['*enormous spout* GREETINGS, SMALL EXPLORER!', '*breaches magnificently* I have traveled 10,000 miles to say hello!', 'My song carries through the entire ocean. Today I sing for you.'],
    bodyColor: '#2B4580',
    accentColor: '#FFFFFF',
    xpReward: 75,
    friendshipLines: ['I will compose a song in your honor!', 'The whole ocean knows your name now.'],
    companionThreshold: 5,
  },

  // ── Acadia National Park, Maine ─────────────────────────────────
  {
    id: 'porcupine',
    name: 'Penny the Porcupine',
    type: 'porcupine',
    emoji: '🦔',
    rarity: 'rare',
    locationIds: ['acadia'],
    funFact: 'Porcupines have about 30,000 quills, and each one has tiny backward-facing barbs like a fishhook!',
    greetings: ['Don\'t worry, I only poke things I don\'t like!', 'I\'m actually very soft underneath all these quills.', 'Want to be friends? Just approach slowly. Verrrrry slowly.'],
    bodyColor: '#5C4033',
    accentColor: '#D2B48C',
    xpReward: 45,
    friendshipLines: ['I\'ll never poke a friend!', 'Careful hugs are the best hugs.'],
    companionThreshold: 4,
  },
  {
    id: 'falcon',
    name: 'Finnegan the Peregrine Falcon',
    type: 'falcon',
    emoji: '🦅',
    rarity: 'legendary',
    locationIds: ['acadia'],
    funFact: 'Peregrine falcons are the fastest animals on Earth — they can dive at over 240 miles per hour!',
    greetings: ['SCREEE! I saw you coming from ten miles away!', 'Race me to the cliff top! Oh wait, you can\'t fly.', 'I dive at 240 mph. Please don\'t ask me to slow down.'],
    bodyColor: '#546E7A',
    accentColor: '#FFE082',
    xpReward: 60,
    friendshipLines: ['I\'ll fly slow so you can keep up!', 'You have the heart of a falcon, explorer!'],
    companionThreshold: 5,
  },
  {
    id: 'lynx',
    name: 'Luna the Canada Lynx',
    type: 'lynx',
    emoji: '🐱',
    rarity: 'legendary',
    locationIds: ['acadia'],
    funFact: 'Canada lynxes have huge, furry paws that act like natural snowshoes, letting them walk on top of deep snow!',
    greetings: ['*silent stare* …You have gentle eyes. I trust you.', 'Most people never see me. You must be special.', 'I have waited three days for the right explorer to walk by. Here you are.'],
    bodyColor: '#B8A99A',
    accentColor: '#E8D5B7',
    xpReward: 70,
    friendshipLines: ['You are the rarest kind of human — a kind one.', 'I\'ll watch over the forest for you, always.'],
    companionThreshold: 5,
  },
  {
    id: 'eagle',
    name: 'Edna the Bald Eagle',
    type: 'eagle',
    emoji: '🦅',
    rarity: 'legendary',
    locationIds: ['acadia'],
    funFact: 'Bald eagles build the largest bird nests in North America — some weigh over a ton and are used for 35 years!',
    greetings: ['*soars majestically overhead* I SEE you.', 'I am the symbol of freedom, but I prefer fish.', 'From my nest on the cliff, I watch over all of Acadia.'],
    bodyColor: '#3D2B00',
    accentColor: '#FFFFFF',
    xpReward: 68,
    friendshipLines: ['You are worthy of these skies, explorer.', 'I fly over your path now, keeping watch.'],
    companionThreshold: 5,
  },

  // ── Cancún & Riviera Maya, Mexico ────────────────────────────
  {
    id: 'seaturtle',
    name: 'Marina the Green Sea Turtle',
    type: 'seaturtle',
    emoji: '🐢',
    rarity: 'rare',
    locationIds: ['cancun'],
    funFact: 'Green sea turtles return to the exact same beach where they were born — even after swimming thousands of miles away for decades!',
    greetings: ['*paddles gracefully* Welcome to my ocean!', 'I have swum across the whole Atlantic! How far have you traveled?', 'I lay my eggs right here on this sand. Can you keep a secret?'],
    bodyColor: '#2E7D32',
    accentColor: '#A5D6A7',
    xpReward: 45,
    friendshipLines: ['I\'ll lead you to the prettiest coral reef!', 'Ancient friends swim together.'],
    companionThreshold: 4,
  },
  {
    id: 'flamingo',
    name: 'Flora the American Flamingo',
    type: 'flamingo',
    emoji: '🦩',
    rarity: 'rare',
    locationIds: ['cancun'],
    funFact: 'Flamingos are actually born grey — their pink color comes entirely from the shrimp and algae they eat!',
    greetings: ['*stands on one leg* Balance is everything in life!', 'Yes, I am this pink. Yes, it is from shrimp. No, I am not embarrassed.', 'Hello! Have you ever tried standing on one leg for four hours?'],
    bodyColor: '#F48FB1',
    accentColor: '#E91E63',
    xpReward: 40,
    friendshipLines: ['I\'ll stand on one leg just for you!', 'Pink and proud to be your friend!'],
    companionThreshold: 4,
  },
  {
    id: 'parrot',
    name: 'Pablo the Yellow-headed Parrot',
    type: 'parrot',
    emoji: '🦜',
    rarity: 'common',
    locationIds: ['cancun'],
    funFact: 'Parrots don\'t just mimic sounds — they actually understand context! Some parrots have shown the intelligence of a 5-year-old child.',
    greetings: ['¡Hola! Hello! Bonjour! I speak many languages!', 'SQUAWK! I said SQUAWK! That\'s parrot for hello!', 'I\'ve been watching you! You seem very curious. So am I!'],
    bodyColor: '#388E3C',
    accentColor: '#F9A825',
    xpReward: 18,
    friendshipLines: ['Best friend! Best friend! SQUAWK!', 'I\'ll learn your name and shout it to the whole jungle!'],
    companionThreshold: 3,
  },
  {
    id: 'jaguar',
    name: 'Jade the Jaguar',
    type: 'jaguar',
    emoji: '🐆',
    rarity: 'legendary',
    locationIds: ['cancun'],
    funFact: 'Jaguars are the only big cats that kill by biting through their prey\'s skull — their bite is stronger than a lion or tiger\'s!',
    greetings: ['*melts out of the shadows* I have been here the whole time.', 'Very few explorers earn a jaguar\'s trust. Let us see if you are worthy.', 'The Mayan people believed jaguars connected the living world to the spirit world. I believe it too.'],
    bodyColor: '#D4A017',
    accentColor: '#2C1810',
    xpReward: 75,
    friendshipLines: ['You walk with the spirit of the jungle now.', 'I will protect you in these ancient forests.'],
    companionThreshold: 5,
  },

  // ── Black Forest, Germany ────────────────────────────────────
  {
    id: 'reddeer',
    name: 'Rudolf the Red Deer',
    type: 'reddeer',
    emoji: '🦌',
    rarity: 'rare',
    locationIds: ['black-forest'],
    funFact: 'A red deer stag\'s antlers are the fastest-growing tissue of any mammal — they can grow an inch every two days!',
    greetings: ['*raises head majestically* Guten Tag, explorer.', 'These forests have been my family\'s home for a thousand years.', 'Listen! Can you hear my bugling call echo through the pines?'],
    bodyColor: '#8B4513',
    accentColor: '#DEB887',
    xpReward: 42,
    friendshipLines: ['I will show you the secret clearings!', 'The oldest stag in the forest calls you friend.'],
    companionThreshold: 4,
  },
  {
    id: 'wildboar',
    name: 'Bruno the Wild Boar',
    type: 'wildboar',
    emoji: '🐗',
    rarity: 'common',
    locationIds: ['black-forest'],
    funFact: 'Wild boars use their snouts like powerful shovels — they can dig up roots 10 inches underground in just seconds!',
    greetings: ['SNORT! Don\'t worry, I only charge things I don\'t like!', '*roots enthusiastically in the mud* Best smells are underground!', 'I have found 14 truffles this morning. Personal record!'],
    bodyColor: '#4A3728',
    accentColor: '#8B7355',
    xpReward: 20,
    friendshipLines: ['I\'ll sniff out treasure for you!', 'Mud-bath buddies for life!'],
    companionThreshold: 3,
  },
  {
    id: 'stork',
    name: 'Hilde the White Stork',
    type: 'stork',
    emoji: '🦢',
    rarity: 'rare',
    locationIds: ['black-forest'],
    funFact: 'White storks migrate 12,000 miles from Europe to Africa every year — and return to the exact same nest, sometimes for 30 years!',
    greetings: ['*clacks bill loudly* Willkommen! That\'s welcome in German!', 'I winter in Africa and summer here. I am a world traveler!', 'My nest has been on that same chimney since before your grandparents were born.'],
    bodyColor: '#F5F5F5',
    accentColor: '#D32F2F',
    xpReward: 38,
    friendshipLines: ['I\'ll carry your wishes on my long journey south!', 'Old friends, new adventures!'],
    companionThreshold: 4,
  },
  {
    id: 'europeanfox',
    name: 'Frieda the European Red Fox',
    type: 'europeanfox',
    emoji: '🦊',
    rarity: 'common',
    locationIds: ['black-forest'],
    funFact: 'European foxes are the most widely distributed wild carnivores on Earth — they live on every continent except Antarctica!',
    greetings: ['*peeks from between roots* A clever visitor!', 'I live at the edge of the forest and the village. Best of both worlds!', 'Guten Abend! That\'s good evening. I am more active at dusk.'],
    bodyColor: '#CC5500',
    accentColor: '#FFFFFF',
    xpReward: 15,
    friendshipLines: ['Let\'s be forest-edge friends!', 'I\'ll show you my favorite den!'],
    companionThreshold: 3,
  },

  // ── Hong Kong, China ──────────────────────────────────────────
  {
    id: 'chinesedolphin',
    name: 'Pearl the Chinese White Dolphin',
    type: 'chinesedolphin',
    emoji: '🐬',
    rarity: 'legendary',
    locationIds: ['hong-kong'],
    funFact: 'Chinese white dolphins are born grey, turn spotted as youngsters, and become bubblegum pink as adults — no other dolphin changes color like this!',
    greetings: ['*leaps from the harbour* 你好! That\'s hello in Cantonese!', 'I live right next to one of the busiest ports on Earth. It\'s very loud but I manage!', 'There are fewer than 2,500 of us left. You finding me is very special.'],
    bodyColor: '#FFB6C1',
    accentColor: '#FF69B4',
    xpReward: 70,
    friendshipLines: ['I will splash a rainbow just for you!', 'The harbour\'s rarest friend is yours.'],
    companionThreshold: 5,
  },
  {
    id: 'macaque',
    name: 'Ming the Rhesus Macaque',
    type: 'macaque',
    emoji: '🐒',
    rarity: 'rare',
    locationIds: ['hong-kong'],
    funFact: 'Rhesus macaques have been into space, helped develop vaccines, and taught scientists about blood types — all because their blood is so similar to ours!',
    greetings: ['*scratches head and stares* …Interesting.', 'I live on Kam Shan — Monkey Mountain! Want to visit?', 'My troop has 40 members. We remember every face. I will remember yours.'],
    bodyColor: '#A0826D',
    accentColor: '#E8C99A',
    xpReward: 45,
    friendshipLines: ['You have earned the troop\'s friendship!', 'Come groom me — that\'s how we show we care!'],
    companionThreshold: 4,
  },
  {
    id: 'blackkite',
    name: 'Kai the Black Kite',
    type: 'blackkite',
    emoji: '🦅',
    rarity: 'common',
    locationIds: ['hong-kong'],
    funFact: 'Hong Kong has one of the world\'s highest densities of black kites — thousands of them soar above the city skyscrapers every day!',
    greetings: ['*wheels effortlessly overhead* From up here the whole city is tiny!', 'I ride the thermals above the skyscrapers. Best view in Asia!', 'I snatch fish from the water without even landing. Watch me!'],
    bodyColor: '#5D4037',
    accentColor: '#FF8F00',
    xpReward: 18,
    friendshipLines: ['I\'ll circle above you wherever you go!', 'Sky friends are forever!'],
    companionThreshold: 3,
  },
  {
    id: 'pangolin',
    name: 'Ping the Sunda Pangolin',
    type: 'pangolin',
    emoji: '🦔',
    rarity: 'legendary',
    locationIds: ['hong-kong'],
    funFact: 'Pangolins are the world\'s most trafficked mammal. Their scales are made of keratin — the same material as your fingernails — yet people mistakenly believe they have magical powers.',
    greetings: ['*rolls into a ball* …Oh! Sorry. I get nervous. Hello.', 'Not many people have ever seen me. You must have a very gentle spirit.', 'I ate 20,000 ants last night. My tongue is longer than my whole body!'],
    bodyColor: '#8D6E63',
    accentColor: '#BCAAA4',
    xpReward: 80,
    friendshipLines: ['You are one of the few humans I trust.', 'I will uncurl for you — that is how you know we\'re true friends.'],
    companionThreshold: 5,
  },

  // ── Hidden secret animals ─────────────────────────────────────
  {
    id: 'groundhog',
    name: 'Gabby the Groundhog',
    type: 'groundhog',
    emoji: '🦫',
    rarity: 'rare',
    locationIds: ['prospect-park'],
    funFact: 'Groundhogs can whistle loudly to warn friends of danger — that\'s why they\'re also called "whistle-pigs"!',
    greetings: ['Pssst! I only come out for patient explorers!', '*peeks from burrow* You came back! I knew you would!', 'Six more weeks of friendship? I think so!'],
    bodyColor: '#8B6914',
    accentColor: '#D4A464',
    xpReward: 30,
    friendshipLines: ['I\'ll save you a cozy spot in my burrow!', 'You\'re the only human I trust!'],
    companionThreshold: 4,
    hidden: true,
    minVisits: 3,
  },
  {
    id: 'heron',
    name: 'Henry the Great Blue Heron',
    type: 'heron',
    emoji: '🦢',
    rarity: 'legendary',
    locationIds: ['central-park'],
    funFact: 'Great blue herons stand perfectly still for minutes at a time, then strike at fish faster than you can blink!',
    greetings: ['…You have been patient. I respect that.', '*stands very still* I have been watching the pond all morning.', 'Only patient explorers find me. You have waited well.'],
    bodyColor: '#78909C',
    accentColor: '#B0BEC5',
    xpReward: 50,
    friendshipLines: ['Stillness is a superpower. You are learning it.', 'I will show you where the fish are happiest.'],
    companionThreshold: 5,
    hidden: true,
    minVisits: 3,
  },
  {
    id: 'sandpiper',
    name: 'Pip the Sandpiper',
    type: 'sandpiper',
    emoji: '🐦',
    rarity: 'rare',
    locationIds: ['rockaway-beach'],
    funFact: 'Sandpipers sprint along the waterline so fast their legs blur — they can take 60 steps per second!',
    greetings: ['Breeep! Breeep! You noticed me!', 'I run SO FAST! Want to race? You won\'t win!', 'I\'ve run 4 miles on this beach today. I\'m just warming up.'],
    bodyColor: '#BCAAA4',
    accentColor: '#FFF8E1',
    xpReward: 35,
    friendshipLines: ['I\'ll run in circles just for you!', 'Only fast explorers find me!'],
    companionThreshold: 4,
    hidden: true,
    minVisits: 3,
  },
  {
    id: 'firefly',
    name: 'Flo the Firefly',
    type: 'firefly',
    emoji: '✨',
    rarity: 'legendary',
    locationIds: ['hudson-valley'],
    funFact: 'Fireflies make light using a chemical called luciferin — their light produces almost no heat at all!',
    greetings: ['*blinks gently* Hello, quiet explorer.', 'I only glow for people who know how to be still.', 'I\'ve been lighting this valley for three summers. You\'re the first to really notice.'],
    bodyColor: '#F9CA24',
    accentColor: '#FFFDE7',
    xpReward: 55,
    friendshipLines: ['I\'ll light your path always!', 'You\'re as bright as a starry night!'],
    companionThreshold: 5,
    hidden: true,
    minVisits: 3,
  },
];

export const getAnimalById = (id: string): Animal | undefined =>
  ANIMALS.find((a) => a.id === id);

export const getAnimalsForLocation = (locationId: string): Animal[] =>
  ANIMALS.filter((a) => a.locationIds.includes(locationId));
